name: Deploy React App to S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repo
      uses: actions/checkout@v3

    # Step 2: Setup Node.js
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Build React app
    - name: Build
      run: npm run build

    # Step 5: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 6: Deploy build folder to S3
    - name: Deploy to S3
      run: |
        aws s3 sync dist/ s3://app.pekinledger.com --delete --exact-timestamps
      # No --acl, works with bucket owner enforced

    # Step 7: Invalidate CloudFront
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id E2CYR3GJ55E8P6 --paths "/*"

    # Step 8: Cache node modules
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
         ${{ runner.os }}-node-
